# Note:
#
# Please keep rules alphabetized within their sections (Style, Metrics, etc)
# Please keep sections alphabetized and separated from other sections

require:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - gemfiles/**/*

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 16

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 16

Minitest/MultipleAssertions:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
