name: Publish documentation

on:
  push:

    # Publish documentation updates when associated code is merged to master
    # or an alternative trunk-like branch in case its changed in the future
    branches:
      - master
      - main

    # Only execute publishing workflow if documentation is updated (Optional)
    paths:
      - docs/**
      - mkdocs.yml
      - .github/workflows/docs.yml

jobs:
  docs:
    uses: appfolio/developer-knowledge-platform/.github/workflows/docs-deploy.yml@latest
    with:
      entity_name: ae-bank-days
    secrets: inherit
